services:
  postgres_db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
#      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

  habit-tracker:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    image: habit-tracker:latest
    container_name: habit-tracker
    depends_on:
      - postgres_db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      APP_ADMIN_USERNAME: ${APP_ADMIN_USERNAME}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
    ports:
      - "1200:8080"
    volumes:
      - ../uploads:/app/uploads
    restart: unless-stopped

volumes:
  db_data:
