--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: habituser
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


ALTER TABLE public.categories OWNER TO habituser;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: habituser
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: goals; Type: TABLE; Schema: public; Owner: habituser
--

CREATE TABLE public.goals (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


ALTER TABLE public.goals OWNER TO habituser;

--
-- Name: goals_id_seq; Type: SEQUENCE; Schema: public; Owner: habituser
--

ALTER TABLE public.goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: habit_entries; Type: TABLE; Schema: public; Owner: habituser
--

CREATE TABLE public.habit_entries (
    id bigint NOT NULL,
    date date NOT NULL,
    habit_id bigint NOT NULL
);


ALTER TABLE public.habit_entries OWNER TO habituser;

--
-- Name: habit_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: habituser
--

ALTER TABLE public.habit_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.habit_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: habit_streaks; Type: TABLE; Schema: public; Owner: habituser
--

CREATE TABLE public.habit_streaks (
    id bigint NOT NULL,
    end_date date NOT NULL,
    start_date date NOT NULL,
    habit_id bigint NOT NULL
);


ALTER TABLE public.habit_streaks OWNER TO habituser;

--
-- Name: habit_streaks_id_seq; Type: SEQUENCE; Schema: public; Owner: habituser
--

ALTER TABLE public.habit_streaks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.habit_streaks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: habits; Type: TABLE; Schema: public; Owner: habituser
--

CREATE TABLE public.habits (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    priority integer,
    start_date date,
    frequency_type character varying(255),
    frequency_value integer,
    category_id bigint,
    goal_id bigint,
    CONSTRAINT habits_frequency_type_check CHECK (((frequency_type)::text = ANY ((ARRAY['DAILY'::character varying, 'WEEKLY'::character varying, 'MONTHLY'::character varying, 'YEARLY'::character varying])::text[])))
);


ALTER TABLE public.habits OWNER TO habituser;

--
-- Name: habits_id_seq; Type: SEQUENCE; Schema: public; Owner: habituser
--

ALTER TABLE public.habits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.habits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: habituser
--

COPY public.categories (id, description, name) FROM stdin;
\.


--
-- Data for Name: goals; Type: TABLE DATA; Schema: public; Owner: habituser
--

COPY public.goals (id, description, name) FROM stdin;
\.


--
-- Data for Name: habit_entries; Type: TABLE DATA; Schema: public; Owner: habituser
--

COPY public.habit_entries (id, date, habit_id) FROM stdin;
\.


--
-- Data for Name: habit_streaks; Type: TABLE DATA; Schema: public; Owner: habituser
--

COPY public.habit_streaks (id, end_date, start_date, habit_id) FROM stdin;
\.


--
-- Data for Name: habits; Type: TABLE DATA; Schema: public; Owner: habituser
--

COPY public.habits (id, description, name, priority, start_date, frequency_type, frequency_value, category_id, goal_id) FROM stdin;
\.


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: habituser
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, false);


--
-- Name: goals_id_seq; Type: SEQUENCE SET; Schema: public; Owner: habituser
--

SELECT pg_catalog.setval('public.goals_id_seq', 1, false);


--
-- Name: habit_entries_id_seq; Type: SEQUENCE SET; Schema: public; Owner: habituser
--

SELECT pg_catalog.setval('public.habit_entries_id_seq', 4, true);


--
-- Name: habit_streaks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: habituser
--

SELECT pg_catalog.setval('public.habit_streaks_id_seq', 4, true);


--
-- Name: habits_id_seq; Type: SEQUENCE SET; Schema: public; Owner: habituser
--

SELECT pg_catalog.setval('public.habits_id_seq', 1, false);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: habituser
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: habituser
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);


--
-- Name: habit_entries habit_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: habituser
--

ALTER TABLE ONLY public.habit_entries
    ADD CONSTRAINT habit_entries_pkey PRIMARY KEY (id);


--
-- Name: habit_streaks habit_streaks_pkey; Type: CONSTRAINT; Schema: public; Owner: habituser
--

ALTER TABLE ONLY public.habit_streaks
    ADD CONSTRAINT habit_streaks_pkey PRIMARY KEY (id);


--
-- Name: habits habits_pkey; Type: CONSTRAINT; Schema: public; Owner: habituser
--

ALTER TABLE ONLY public.habits
    ADD CONSTRAINT habits_pkey PRIMARY KEY (id);


--
-- Name: habit_streaks fke44kxc36318bnse402vsj0f5g; Type: FK CONSTRAINT; Schema: public; Owner: habituser
--

ALTER TABLE ONLY public.habit_streaks
    ADD CONSTRAINT fke44kxc36318bnse402vsj0f5g FOREIGN KEY (habit_id) REFERENCES public.habits(id);


--
-- Name: habits fkf6uni342qd7oaavv2tg75e1tc; Type: FK CONSTRAINT; Schema: public; Owner: habituser
--

ALTER TABLE ONLY public.habits
    ADD CONSTRAINT fkf6uni342qd7oaavv2tg75e1tc FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: habits fkjeuc8h34b3hire0wlw4ou9w3m; Type: FK CONSTRAINT; Schema: public; Owner: habituser
--

ALTER TABLE ONLY public.habits
    ADD CONSTRAINT fkjeuc8h34b3hire0wlw4ou9w3m FOREIGN KEY (goal_id) REFERENCES public.goals(id);


--
-- Name: habit_entries fkqyogm6s0qci12sn22gn7bwwuq; Type: FK CONSTRAINT; Schema: public; Owner: habituser
--

ALTER TABLE ONLY public.habit_entries
    ADD CONSTRAINT fkqyogm6s0qci12sn22gn7bwwuq FOREIGN KEY (habit_id) REFERENCES public.habits(id);


--
-- PostgreSQL database dump complete
--

