BEGIN;

ALTER TABLE public.goals
    ADD COLUMN IF NOT EXISTS year      INTEGER NULL,
    ADD COLUMN IF NOT EXISTS progress  INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS priority  INTEGER NULL,
    ADD COLUMN IF NOT EXISTS done      BOOLEAN NOT NULL DEFAULT FALSE;

-- Sub-Goals Tabelle
CREATE TABLE IF NOT EXISTS public.sub_goals (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id   BIGINT NOT NULL,
    name      VARCHAR(255) NOT NULL,
    year      INTEGER NULL,
    quarter   VARCHAR(3)  NULL,   -- 'Q1'..'Q4' (optional)
    month     VARCHAR(20) NULL,   -- 'JANUARY'..'DECEMBER' (optional)
    progress  INTEGER NOT NULL DEFAULT 0,
    done      BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT sub_goals_progress_range CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT fk_sub_goals_goal
        FOREIGN KEY (goal_id) REFERENCES public.goals(id) ON DELETE CASCADE
);

-- optional: Wertebereich für quarter erzwingen
ALTER TABLE public.sub_goals
    ADD CONSTRAINT sub_goals_quarter_check
        CHECK (quarter IS NULL OR quarter IN ('Q1','Q2','Q3','Q4'));

COMMIT;
